site_name: Challenge Documentation
extra_css: 
    - stylesheets/extra.css

theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: teal

markdown_extensions:
    - attr_list
    - pymdownx.tabbed
    - pymdownx.superfences

nav:
    - Home: index.md
    - Weekly Recaps:
        - 1. Sept 28th - Oct 4th : 'weeklyRecaps/week1.md'
        - 2. Oct 5th - Oct 11th : 'weeklyRecaps/week2.md'
